In [26]:
# Importing required libraries
import numpy as np  # For numerical computations and array operations
import pandas as pd  # For data manipulation and analysis
from functools import reduce  # For functional programming utilities
import re  # For regular expressions and pattern matching


In [27]:
import matplotlib.pyplot as plt  # For data visualization


1. Python Functions

In [28]:
# Function with parameters and return value
def add_numbers(a, b):
    return a + b
print("Sum:", add_numbers(5, 10))


Sum: 15


In [29]:
# Function with default argument
def greet(name="Guest"):
    print(f"Hello, {name}!")
greet()
greet("Alice")

Hello, Guest!
Hello, Alice!


In [30]:
# Recursive function
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n - 1)
print("Factorial of 5:", factorial(5))

Factorial of 5: 120


In [31]:
 # Function scope demonstration
def myfunc1():
  x = "Jane"
  def myfunc2():
    nonlocal x
    x = "hello"
  myfunc2()
  return x

print(myfunc1())

# Function Global scope demonstration


def myfunc():
  global x
  x = 300

myfunc()

print(x)

hello
300


In [32]:
# Docstring example
def multiply(a, b):
    """This function multiplies two numbers."""
    return a * b
help(multiply)

Help on function multiply in module __main__:

multiply(a, b)
    This function multiplies two numbers.



2. Lambda Functions

In [33]:
# Simple lambda function
square = lambda x: x * x
print("Square of 4:", square(4))



Square of 4: 16


In [34]:
# Using lambda with map
numbers = [1, 2, 3, 4]
squared = list(map(lambda x: x**2, numbers))
print("Squared numbers:", squared)



Squared numbers: [1, 4, 9, 16]


In [35]:
# Using lambda with filter
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even numbers:", even_numbers)



Even numbers: [2, 4]


In [36]:
# Using lambda with reduce
from functools import reduce
product = reduce(lambda x, y: x * y, numbers)
print("Product of numbers:", product)


Product of numbers: 24


3. NumPy



In [37]:
import numpy as np

# Create arrays
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2], [3, 4]])
print("1D Array:", array_1d)
print("2D Array:\n", array_2d)



1D Array: [1 2 3]
2D Array:
 [[1 2]
 [3 4]]


In [38]:
# Arithmetic operations
print("Array + 2:", array_1d + 2)



Array + 2: [3 4 5]


In [39]:
# Indexing and slicing
print("Element at index 1:", array_1d[1])
print("Slice:", array_2d[0, :])



Element at index 1: 2
Slice: [1 2]


In [40]:
# Array manipulation
reshaped = array_1d.reshape(3, 1)
print("Reshaped array:\n", reshaped)



Reshaped array:
 [[1]
 [2]
 [3]]


In [41]:
# Random number generator
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)


Random Array:
 [[0.94922626 0.89065052 0.80968861]
 [0.21394262 0.499866   0.07311438]
 [0.92022931 0.86306842 0.12659376]]


4. Pandas

In [42]:
import pandas as pd

# Create DataFrame
data = {"Name": ["Alice", "Bob"], "Age": [25, 30]}
df = pd.DataFrame(data)
print(df)




    Name  Age
0  Alice   25
1    Bob   30


In [43]:
file_path = '/sample_order_data.csv'  # Update with your file name
df=pd.read_csv(file_path)
df.head(5)

OrderID  CustomerID   OrderDate  ProductID ProductName  Quantity  \
0      101        1001  2023-01-01       2001   Product A         1   
1      102        1002  2023-01-02       2002   Product B         2   
2      103        1003  2023-01-03       2003   Product C         3   
3      104        1004  2023-01-04       2004   Product D         4   
4      105        1005  2023-01-05       2001   Product A         2   

   UnitPrice  TotalPrice  
0       10.0        10.0  
1       15.5        31.0  
2       12.0        36.0  
3        9.5        38.0  
4       10.0        20.0

In [44]:
df.fillna(0, inplace=True)

In [45]:
pivot_table = df.pivot_table(
    index="CustomerID",        # Rows
    columns="ProductName",    # Columns
    values="Quantity",        # Values to aggregate
    aggfunc="sum",            # Aggregation function
    fill_value=0              # Fill NaN with 0
)
# Reset the index for better readability
pivot_table.reset_index(inplace=True)

# Display the pivoted DataFrame
print(pivot_table)

ProductName  CustomerID  Product A  Product B  Product C  Product D
0                  1001          1          3          2          0
1                  1002          0          2          1          4
2                  1003          2          0          3          4
3                  1004          3          3          0          4
4                  1005          2          1          1          0


5. If Statements

In [46]:
age = 20
if age < 18:
    print("Minor")
elif age >= 18 and age < 60:
    print("Adult")
else:
    print("Senior Citizen")

Adult


6. Loops

In [47]:
# For loop
for i in range(5):
    print("For loop iteration:", i)




For loop iteration: 0
For loop iteration: 1
For loop iteration: 2
For loop iteration: 3
For loop iteration: 4


In [48]:
# While loop
count = 0
while count < 3:
    print("Count:", count)
    count += 1



Count: 0
Count: 1
Count: 2


In [49]:
# Nested loop
for i in range(2):
    for j in range(2):
        print(f"i={i}, j={j}")

i=0, j=0
i=0, j=1
i=1, j=0
i=1, j=1


7. Lists, Tuples, Sets, Dictionaries


In [50]:
# Lists
lst = [1, 2, 3]
lst.append(4)
print("List:", lst)

# Tuples
tpl = (1, 2, 3)
print("Tuple:", tpl)

# Sets
st = {1, 2, 3}
st.add(4)
print("Set:", st)

# Dictionaries
dct = {"key1": "value1"}
dct["key2"] = "value2"
print("Dictionary:", dct)



List: [1, 2, 3, 4]
Tuple: (1, 2, 3)
Set: {1, 2, 3, 4}
Dictionary: {'key1': 'value1', 'key2': 'value2'}


8. Operators

In [51]:
a, b = 10, 20

# Arithmetic
print("Addition:", a + b)

# Comparison
print("Equal:", a == b)

# Logical
print("Logical AND:", a > 5 and b > 15)

# Assignment
a += 5
print("Updated a:", a)


Addition: 30
Equal: False
Logical AND: True
Updated a: 15


 9. Reading CSV Files

In [52]:
from google.colab import files
import pandas as pd

file_path = '/sample_order_data.csv'  # Update with your file name
df=pd.read_csv(file_path)
df.head(5)

OrderID  CustomerID   OrderDate  ProductID ProductName  Quantity  \
0      101        1001  2023-01-01       2001   Product A         1   
1      102        1002  2023-01-02       2002   Product B         2   
2      103        1003  2023-01-03       2003   Product C         3   
3      104        1004  2023-01-04       2004   Product D         4   
4      105        1005  2023-01-05       2001   Product A         2   

   UnitPrice  TotalPrice  
0       10.0        10.0  
1       15.5        31.0  
2       12.0        36.0  
3        9.5        38.0  
4       10.0        20.0

10. Python String Methods

In [53]:
text = "  Hello, World!  "

# Remove whitespace
print(text.strip())

# Uppercase
print(text.upper())

# Slicing
print(text[:5])

# Find
print(text.find("World"))


Hello, World!
  HELLO, WORLD!  
  Hel
9
